### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by ataut** [einbond/SPARCL#1]
Are there install instructions for dependencies like spat5?

**Comment by einbond** [comment]
Thanks @ataut , yes, Spat5 and osc-route.mxo from CNMAT Tools (because spat5.osc-route has not implemented all of the features of the original osc-route). Sorry I am a GitHub novice so I have to learn how to specify those dependencies in the repository!

**Comment by ataut** [comment]
Non worries - perhaps just mention them and put links or instructions in the ReadMe :-)

**Comment by ataut** [comment]
@einbond  Strange, I've got the CNMAT Externals installed via package manager and don't see spat5....

**Comment by einbond** [comment]
Sorry for the grammatical infelicity: only osc-route.mxo is needed from the CNMAT Externals and spat5 is available from https://forum.ircam.fr/projects/detail/spat/ (with a free login)

**Comment by einbond** [comment]
9ed862b removed CNMAT Externals (osc-route) dependency and added spat5 link to README.
